version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/db
    networks:
      - app-network
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - api
    networks:
      - app-network
    command: npm run dev
    volumes:
      - ./front-end:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge
